/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assign1Java;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        System.out.println("Enter a number to find if a number is a perfect number or not: ");
        Scanner scanner = new Scanner(System.in);
        long number = scanner.nextLong();
        System.out.println("Imperative: " + number + (isPerfectNumber_Imperative(number) ? " is a "  : " is not a ") + "perfect number.");
        System.out.println("Functional: " + number + (isPerfectNumber_Functional(number) ? " is a "  : " is not a ") + "perfect number.");
        scanner.close();
    }

	//imperative method
	static boolean isPerfectNumber_Imperative(long number) {
        if (number > 1){
          long sumOfFactors = 0;
          for (long i=1; i <= number; i++ ){
            if (number % i == 0)
              sumOfFactors += i; 
          }
          if (sumOfFactors == number*2)
            return true;
          else
            return false;
        } else {
          return false;
        }
    }

	//functional method
    static boolean isPerfectNumber_Functional(long number) {
        if(number > 1){
          if(isPerfectRecurssive(number, 1, 0) == number*2){
            return true;
          } else{
            return false;
          }
        } else{
          return false;
        }
    }

    static long isPerfectRecurssive(long number, long i, long sumOfFactors)
    {
        if (i > number)
            return sumOfFactors;
        else{
            if(number % i == 0)
                return isPerfectRecurssive(number, i+1, sumOfFactors+i);
            else
                return isPerfectRecurssive(number, i+1, sumOfFactors);
        }
    }
}
